name: Build for release

on:
  workflow_dispatch:
  push:
    branches:
     - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: sudo apt-get install --assume-yes gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi libgnutls28-dev uuid-dev
    - name: Download source code
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: Build
      run: make
    - name: Create release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        sha256sum $GITHUB_WORKSPACE/trusted-firmware-a/build/a3700/release/flash-image.bin | head --bytes=64 > sha256sum.txt
        gh release create "$(date +'%Y.%m.%d')" \
            --generate-notes \
            $GITHUB_WORKSPACE/trusted-firmware-a/build/a3700/release/flash-image.bin \
            sha256sum.txt
